// TODO move to models folder
export interface Automation {
  /** Name for the UI */
  name: string;
  /** Generated by the Backend */
  id?: string;
  /** Wether the automation is executed or not */
  active: boolean;
  /** Date in **ISO format** before which the automation never get's executed */
  startDate?: string;
  /** Date in **ISO format** after which the automation never get's executed */
  endDate?: string;
  /** The actions which are part of the automation */
  actions: Array<DeviceStateAutomationAction
    | MqttMessageAutomationAction>;
}

export interface DeviceStateAutomationAction {
  /** Name for the UI */
  name: string;
  /** Generated by the Backend */
  id: string;
  /** Schedule string in cron format */
  schedule: string;
  /** Priority of the action */
  priority: number;
  /** Type of the action */
  type: 'deviceState';
  /** States that are applied by the action */
  states: Array<{
    /** Id of the device that the state changed is applied to */
    deviceId: string;
    /** State which get's applied to the device */
    states: Array<{
      /** Id of the input that the state changed is applied to */
      inputId: string;
      /** Value of the state change */
      value: string;
    }>;
  }>;
}

export interface MqttMessageAutomationAction {
  /** Name for the UI */
  name: string;
  /** Generated by the Backend */
  id: string;
  /** Schedule string in cron format */
  schedule: string;
  /** Priority of the action */
  priority: number;
  /** Type of the action */
  type: 'mqttMessage';
  /** Topic the MQTT message get's send to */
  topic: string;
  /** Payload of the MQTT message that get's send */
  payload: string;
}
